name: 'ayleio'
description: 'ayleio is program for help you, booster up your projects significants with amazing features and super easy for use'
version: '0.0.0'
homepage: 'https://youtube.com/@azkadev'
repository: 'https://github.com/azkadev/ayleio'
issue_tracker: 'https://github.com/azkadev/ayleio/issues'
documentation: 'https://github.com/azkadev/ayleio'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://www.patreon.com/c/azkadev'
  - 'https://opencollective.com/azkadev'
  - 'https://paypal.me/azkadev'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  collection: '>=1.19.0 <=5.0.0'
  ffi: '^2.1.4'
  flutter:
    sdk: 'flutter'
  meta: '^1.16.0'
  path: '^1.9.0'
  volume_controller: '>=3.4.0 <=5.0.0'
  wakelock_plus: '>=1.2.10 <=5.0.0'
  web: '^1.1.1'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
project:
  type: ''
  is_use_direct_package: false
  is_private: false
  developers:
    - username: ''
      note: ''
      social_medias:
        - 'https://github.com'